### ISSUE TITLE
Support for Android 12 emulation?

### ISSUE THREAD

**Issue by dinzdale** [gektor650/OkHttpProfiler-AndroidStudio-Plugin#4]
Love this plugin!!!
Doesn't seem to work with Android 12 emulation.

Also, can I contribute via Paypal. Really don't want to
post my credit card to another service. 

Thanks,
Gary
xtraxtra@comcast.net

**Comment by eugene-tkachenko** [comment]
Fixed.
It is waiting for JetBrain's review.
You can manually install it by URL:
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/155508
The issue was with the new studio, there was no issue with android 12.

P.s. I added Paypal to this page & to the plugin 
https://www.paypal.com/donate/?business=T9DG8B4C6BX8C&no_recurring=0&currency_code=USD
Feel free to ping if you have issues with the new version
